version: '3.8'
networks: 
  apinetwork: {}
services:
  restful_api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on: 
      - serverdb
    networks:
      - apinetwork

  serverdb:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=f5demo
    ports:
      - '5432:5432'
    volumes: 
      - serverdb:/var/lib/postgresql/data
    networks:
      - apinetwork
volumes:
  serverdb:
    driver: local